version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spisop
      MYSQL_USER: spisopuser
      MYSQL_PASSWORD: spisoppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_net

volumes:
  mysql_data:

networks:
  mysql_net:
