name: Create PR on Branch Push

on:
  push:
    branches:
      - '**'  # Runs on all branches except main (handled in the workflow)

jobs:
  create_pr:
    if: github.ref != 'refs/heads/main'  # Only run if the push is NOT to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Check for commits
        run: |
          git fetch origin main
          if [ -z "$(git log origin/main..${GITHUB_REF##*/} --oneline)" ]; then
            echo "No new commits to create a pull request."
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ env.BRANCH_NAME }}
          title: "Automated PR for branch: ${{ env.BRANCH_NAME }}"
          body: "This is an automated pull request created from branch: ${{ env.BRANCH_NAME }}."
