name: Create Pull Request on New Branch

on:
  push:
    branches-ignore:
      - master
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: write  # Ensure the workflow can write and create PRs

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: master
          title: "Pull request for new branch: ${{ github.ref_name }}"
          body: |
            This pull request was created automatically when the branch `${{ github.ref_name }}` was pushed.
