name: Run Spring Boot Tests (Maven)

on:
  push:
    branches:
      - "**"  # Runs on any branch push
  pull_request:
    branches:
      - "**"  # Runs on any pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17  # You can change this to any version your project requires
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Step 4: Run Maven test
      - name: Run Maven tests
        run: mvn clean test
