name: Run Postman Tests

on: push

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can change to '16' or '18' if needed

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run the Postman collection using Newman
      - name: Run Postman Collection
        run: newman run src/test/API/postman_collection.json
