name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java 17 for Spring Boot, adjust the version as necessary)
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Or adopt-openjdk or other distributions
          java-version: '22'

      # Step 3: Set up Node.js for API tests (use version 16 or higher)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust Node.js version as needed

      # Step 4: Install dependencies for Maven
      - name: Install Maven dependencies
        run: mvn install

      # Step 5: Run Spring Boot Unit Tests using Maven
      - name: Run Unit Tests
        run: mvn test  # This will run all your Spring Boot tests
        continue-on-error: false  # Stop if unit tests fail

      # Step 6: Install Newman for running API tests
      - name: Install Newman
        run: npm install -g newman

      # Step 7: Run API Tests using Newman (Postman collections)
      #- name: Run API Tests
      #  run: newman run ./path/to/your-api-collection.postman_collection.json \
      #    --env-var "base_url=${{ secrets.PROD_BASE_URL }}" \
      #    --env-var "api_key=${{ secrets.PROD_API_KEY }}"