name: Run Tests

on:
  push:
    branches:
      - '**'  # Runs on all branches
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch (no tests run here)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches to ensure we can access main

      # Step 2: Set up JDK for Java-based tests
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Maven dependencies (without running tests)
      - name: Install Maven dependencies
        run: mvn install -DskipTests

      # Step 5: Set environment variables for H2 and your application
      - name: Set Environment Variables
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

      # Step 6: Start your application (API)
      - name: Start Application
        run: |
          mvn spring-boot:run &  # Start the application in the background
          sleep 20 # wait for the app to start

      # Step 7: Run Unit Tests (Only on push events)
      - name: Run Unit Tests
        if: github.event_name == 'push'  # Run tests only on push
        run: mvn test

      # Step 8: Install Postman CLI (Only on pull requests to main)
      - name: Install Postman CLI
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Step 9: Login to Postman CLI using API key from GitHub Secrets (Only on pull requests to main)
      - name: Login to Postman CLI
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Step 10: Run Postman API Tests using the test database (Only on pull requests to main)
      - name: Run API tests
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          postman collection run "27701941-bcda9707-2e28-4e8c-9e39-176f60c7310c" -e "27701941-ab771043-acdc-4f32-a19e-3d0f50e03b3" \
            --env-var base_url="$BASE_URL"
