name: Run API Tests

on:
  push:
    branches:
      - '**'  # Runs on all branches except main
      - '!main'  # Excludes the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches to ensure we can access main

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Set Environment Variables
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

      # Step 6: Start your application (API) only if it's a push event
      - name: Start Application
        run: |
          mvn spring-boot:run &  # Start the application in the background
          sleep 20 # wait for the app to start

      # Step 7: Run Unit Tests (Always run on branches except main)
      - name: Run Unit Tests
        run: mvn test

      # Step 8: Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Step 9: Login to Postman CLI using API key from GitHub Secrets
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Step 10: Run Postman API Tests using the test database
      - name: Run API tests
        run: |
          postman collection run "27701941-bcda9707-2e28-4e8c-9e39-176f60c7310c" -e "27701941-ab771043-acdc-4f32-a19e-3d0f50e03b3c" \
            --env-var base_url="$BASE_URL"
