name: Run Tests with H2 and API

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Java-based tests
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Maven dependencies (without running tests)
      - name: Install Maven dependencies
        run: mvn install -DskipTests

      # Step 5: Set environment variables for H2 and your application
      - name: Set Environment Variables
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "BASE_URL=http://localhost:8080" >> $GITHUB_ENV

      # Step 6: Start your application (API)
      - name: Start Application
        run: |
          mvn spring-boot:run &
          sleep 30 # wait for the app to start

      # Step 7: Run Unit Tests
      - name: Run Unit Tests
        run: mvn test

      # Step 8: Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Step 9: Login to Postman CLI using API key from GitHub Secrets
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Step 10: Run Postman API Tests
      - name: Run API tests
        run: |
          postman collection run "your_collection_id" -e "your_environment_id" \
            --env-var base_url="$BASE_URL"
